export type GO = LuaUserdata;
export type GUI_NODE = string | node;

export type ANIMATION_PLAYBACKS = 'PLAYBACK_LOOP_BACKWARD' | 'PLAYBACK_LOOP_FORWARD' | 'PLAYBACK_LOOP_PINGPONG' | 'PLAYBACK_ONCE_BACKWARD' | 'PLAYBACK_ONCE_FORWARD' | 'PLAYBACK_ONCE_PINGPONG' | 'PLAYBACK_LOOP_PINGPONG' | 'PLAYBACK_LOOP_FORWARD' | 'PLAYBACK_LOOP_BACKWARD';
export type ANIMATION_EASINGS = 'EASING_LINEAR' |
    'EASING_INBACK' | 'EASING_OUTBACK' |
    'EASING_INOUTBACK' | 'EASING_OUTINBACK' |
    'EASING_INBOUNCE' | 'EASING_OUTBOUNCE' |
    'EASING_INOUTBOUNCE' | 'EASING_OUTINBOUNCE' |
    'EASING_INELASTIC' | 'EASING_OUTELASTIC' |
    'EASING_INOUTELASTIC' | 'EASING_OUTINELASTIC' |
    'EASING_INSINE' | 'EASING_OUTSINE' |
    'EASING_INOUTSINE' | 'EASING_OUTINSINE' |
    'EASING_INEXPO' | 'EASING_OUTEXPO' |
    'EASING_INOUTEXPO' | 'EASING_OUTINEXPO' |
    'EASING_INCIRC' | 'EASING_OUTCIRC' |
    'EASING_INOUTCIRC' | 'EASING_OUTINCIRC' |
    'EASING_INQUAD' | 'EASING_OUTQUAD' |
    'EASING_INOUTQUAD' | 'EASING_OUTINQUAD' |
    'EASING_INCUBIC' | 'EASING_OUTCUBIC' |
    'EASING_INOUTCUBIC' | 'EASING_OUTINCUBIC' |
    'EASING_INQUART' | 'EASING_OUTQUART' |
    'EASING_INOUTQUART' | 'EASING_OUTINQUART' |
    'EASING_INQUINT' | 'EASING_OUTQUINT' |
    'EASING_INOUTQUINT' | 'EASING_OUTINQUINT';

export type ANIMATION_DATA = {
    value: vmath.vector3 | vmath.vector4,
    easing: ANIMATION_EASINGS,
    duration: number,
    delay: number,
    playback: ANIMATION_PLAYBACKS,
    compliteFunc: (() => void) | null
};