local ____exports = {}
local druid = require("druid.druid")
local ____DailyBonuses = require("logic.advanced.DailyBonuses")
local DailyBonuses = ____DailyBonuses.DailyBonuses
function ____exports.init(_this)
    Manager.init_script()
    _this.druid = druid.new(_this)
    local node_names = {}
end
function ____exports.on_input(self, action_id, action)
    Camera.transform_input_action(action)
    return self.druid:on_input(action_id, action)
end
function ____exports.update(self, dt)
    self.druid:update(dt)
end
function ____exports.on_message(self, message_id, message, sender)
    self.druid:on_message(message_id, message, sender)
end
function ____exports.final(self)
    DailyBonuses.final()
    Manager.final_script()
    Camera.set_gui_projection(false)
    self.druid:final()
end
init = ____exports.init
on_input = ____exports.on_input
update = ____exports.update
on_message = ____exports.on_message
final = ____exports.final

